.\" Manpage for opendlv-core-signalinjector
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-signalinjector 1 "11 September 2016" "0.0.8" "opendlv-core-signalinjector man page"

.SH NAME
opendlv-core-signalinjector \- This tool interfaces with a vehicle issuing commands read from a csv file.



.SH SYNOPSIS
.B opendlv-core-signalinjector --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-signalinjector --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

