.\" Manpage for opendlv-core-proxy-camera-axis
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-camera-axis 1 "09 April 2018" "0.14.0" "opendlv-core-proxy-camera-axis man page"

.SH NAME
opendlv-core-proxy-camera-axis \- This tool interfaces with Axis cameras.



.SH SYNOPSIS
.B opendlv-core-proxy-camera-axis --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-camera-axis --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

