.\" Manpage for opendlv-core-proxy-ledstrip
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-ledstrip 1 "07 December 2016" "0.7.1" "opendlv-core-proxy-ledstrip man page"

.SH NAME
opendlv-core-proxy-ledstrip \- This tool interfaces with an LED strip.



.SH SYNOPSIS
.B opendlv-core-proxy-ledstrip --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-ledstrip --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

