.\" Manpage for opendlv-core-proxy-fh16truck
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-fh16truck 1 "19 May 2017" "0.9.3" "opendlv-core-proxy-fh16truck man page"

.SH NAME
opendlv-core-proxy-fh16truck \- This tool interfaces with the FH16 truck.



.SH SYNOPSIS
.B opendlv-core-proxy-fh16truck --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-fh16truck --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

