.\" Manpage for opendlv-core-tool-camera-replay
.\" Author: Chalmers Revere <revere@chalmers.se>.

.TH opendlv-core-tool-camera-replay 1 "09 April 2018" "0.14.0" "opendlv-core-tool-camera-replay man page"

.SH NAME
opendlv-core-tool-camera-replay \- This tool replays a video as camera feed.



.SH SYNOPSIS
.B opendlv-core-tool-camera-replay --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-tool-camera-replay --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Chalmers Revere (revere@chalmers.se)

