.\" Manpage for opendlv-core-proxy-velodyne32
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-velodyne32 1 "09 April 2018" "0.14.0" "opendlv-core-proxy-velodyne man page"

.SH NAME
opendlv-core-proxy-velodyne32 \- This tool interfaces with HDL-32E Velodyne 32 LiDAR



.SH SYNOPSIS
.B opendlv-core-proxy-velodyne32 --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-velodyne32 --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

