.\" Manpage for opendlv-core-proxy-steppermotor
.\" Author: 

.TH opendlv-core-proxy-steppermotor 1 "26 September 2017" "0.3.4" "opendlv-core-proxy-steppermotor man page"

.SH NAME
opendlv-core-proxy-steppermotor \- This module interfaces with an steppermotor pin at the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-core-proxy-steppermotor --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-steppermotor --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR


