.\" Manpage for opendlv-core-proxy-applanix
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-applanix 1 "09 April 2018" "0.14.0" "opendlv-core-proxy-applanix man page"

.SH NAME
opendlv-core-proxy-applanix \- This tool interfaces to GPS/IMU unit Applanix.



.SH SYNOPSIS
.B opendlv-core-proxy-applanix --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-applanix --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

