.\" Manpage for opendlv-core-system-health
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-system-health 1 "09 April 2018" "0.14.0" "opendlv-core-system-health man page"

.SH NAME
opendlv-core-system-health \- This component checks the health of the runtime environment.



.SH SYNOPSIS
.B opendlv-core-system-health --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-system-health --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

