# Copyright (C) 2018 Ola Benderius
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

FROM alpine
MAINTAINER Ola Benderius "ola.benderius@chalmers.se"

COPY od4/bin/odCANDataStructureGenerator-latest.jar /usr/bin/
COPY od4/bin/odDataStructureGenerator-latest.jar /usr/bin/

COPY od4/include/odcantools /usr/include
COPY od4/include/opendavinci /usr/include

COPY od4/lib/libodcantools.so /usr/lib/
COPY od4/lib/libopendavinci.so /usr/lib/

COPY od4/share/cmake-2.8/Modules/FindOpenDaVINCI.cmake /usr/share/cmake-2.8/Modules/
COPY od4/share/cmake-2.8/Modules/FindLibRT.cmake /usr/share/cmake-2.8/Modules/
COPY od4/share/cmake-2.8/Modules/FindodCANDataStructureGenerator.cmake /usr/share/cmake-2.8/Modules/
COPY od4/share/cmake-2.8/Modules/FindodDataStructureGenerator.cmake /usr/share/cmake-2.8/Modules/
COPY od4/share/cmake-3.0/Modules/FindOpenDaVINCI.cmake /usr/share/cmake-3.0/Modules/
COPY od4/share/cmake-3.0/Modules/FindLibRT.cmake /usr/share/cmake-3.0/Modules/
COPY od4/share/cmake-3.0/Modules/FindodCANDataStructureGenerator.cmake /usr/share/cmake-3.0/Modules/
COPY od4/share/cmake-3.0/Modules/FindodDataStructureGenerator.cmake /usr/share/cmake-3.0/Modules/
COPY od4/share/cmake-3.5/Modules/FindOpenDaVINCI.cmake /usr/share/cmake-3.5/Modules/
COPY od4/share/cmake-3.5/Modules/FindLibRT.cmake /usr/share/cmake-3.5/Modules/
COPY od4/share/cmake-3.5/Modules/FindodCANDataStructureGenerator.cmake /usr/share/cmake-3.5/Modules/
COPY od4/share/cmake-3.5/Modules/FindodDataStructureGenerator.cmake /usr/share/cmake-3.5/Modules/

COPY include /usr/include
COPY lib /usr/lib
COPY share /usr/share

RUN apk add --update cmake g++ gcc make openjdk8-jre
