# Dockerfile to create an image for building and running OpenDLV core.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

FROM BASEIMAGE
MAINTAINER Christian Berger "christian.berger@gu.se"

ADD include /usr/include
ADD lib /usr/lib
ADD share /usr/share

RUN apt-get update
RUN apt-get -y install docker.io cxxtest witty witty-dev

ADD opendlv-builder.sh /usr/bin/opendlv-builder
RUN chmod +x /usr/bin/opendlv-builder
RUN mkdir /opt/sources

ENV QT_X11_NO_MITSHM=1
