.\" Manpage for opendlv-core-proxy-imu
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-imu 1 "09 April 2018" "0.14.0" "opendlv-core-proxy-imu man page"

.SH NAME
opendlv-core-proxy-imu \- This tool interfaces with a imu.



.SH SYNOPSIS
.B opendlv-core-proxy-imu --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-imu --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

