.\" Manpage for opendlv-core-tool-camera-projection
.\" Author: Chalmers Revere <revere@chalmers.se>.

.TH opendlv-core-tool-camera-projection 1 "09 April 2018" "0.14.0" "opendlv-core-tool-camera-projection man page"

.SH NAME
opendlv-core-tool-camera-projection \- This tool finds the projection matrix from a camera feed.



.SH SYNOPSIS
.B opendlv-core-tool-camera-projection --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-tool-camera-projection --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Chalmers Revere (revere@chalmers.se)

