.\" Manpage for opendlv-core-proxy-anglesensor
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-anglesensor 1 "18 July 2017" "0.10.1" "opendlv-core-proxy-anglesensor man page"

.SH NAME
opendlv-core-proxy-anglesensor \- This tool interfaces with a anglesensor.



.SH SYNOPSIS
.B opendlv-core-proxy-anglesensor --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-anglesensor --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

