.\" Manpage for opendlv-core-proxy-velodyne16
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-velodyne16 1 "09 April 2018" "0.14.0" "opendlv-core-proxy-velodyne man page"

.SH NAME
opendlv-core-proxy-velodyne16 \- This tool interfaces with the VLP-16 Velodyne 16 LiDAR



.SH SYNOPSIS
.B opendlv-core-proxy-velodyne16 --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-velodyne16 --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

