.\" Manpage for opendlv-core-tool-camera-replay
.\" Author: Chalmers Revere <revere@chalmers.se>.

.TH opendlv-core-tool-imu-calibration 1 "12 Nov 2017" "0.10.3" "opendlv-core-tool-imu-calibration man page"

.SH NAME
opendlv-core-tool-imu-calibration \- This tool calculates calibration matrices



.SH SYNOPSIS
.B opendlv-core-tool-imu-calibration  --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-toolmove-imu-calibration -cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Chalmers Revere (revere@chalmers.se)

