.\" Manpage for opendlv-core-proxy-sick
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-sick 1 "09 April 2018" "0.14.0" "opendlv-core-proxy-sick man page"

.SH NAME
opendlv-core-proxy-sick \- This tool interfaces with the Sick lidar device.



.SH SYNOPSIS
.B opendlv-core-proxy-sick --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-sick --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

