.\" Manpage for opendlv-core-proxy-v2v
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-v2v 1 "09 April 2018" "0.14.0" "opendlv-core-proxy-v2v man page"

.SH NAME
opendlv-core-proxy-v2v \- This tool interfaces with a V2V unit.



.SH SYNOPSIS
.B opendlv-core-proxy-v2v --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-v2v --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

