.\" Manpage for opendlv-core-proxy-imu-calibration
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-imu-calibration 1 "12 August 2017" "0.10.3" "opendlv-core-proxy-imu-calibration man page"

.SH NAME
opendlv-core-proxy-imu-calibration \- This tool calibrates IMU data.



.SH SYNOPSIS
.B opendlv-core-proxy-imu-calibration --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-imu-calibration --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

