.\" Manpage for opendlv-core-proxy-beacons
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-beacons 1 "19 October 2016" "0.3.0" "opendlv-core-proxy-beacons man page"

.SH NAME
opendlv-core-proxy-beacons \- This tool interfaces with beacons.



.SH SYNOPSIS
.B opendlv-core-proxy-beacons --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-beacons --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

