.\" Manpage for opendlv-core-proxy-relay
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-relay 1 "19 October 2016" "0.3.0" "opendlv-core-proxy-relay man page"

.SH NAME
opendlv-core-proxy-relay \- This tool interfaces with relays.



.SH SYNOPSIS
.B opendlv-core-proxy-relay --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-relay --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

